{
  imports = [
    ../../shared
    ./host.nix
    ./disk.nix
    ./secrets.nix
    ./nas-client.nix
    ./services/media/shared.nix
    ./services/media/jellyfin-bootstrap.nix
    ./services/media/jellyfin-plugins.nix
    ./services/media/jellyfin-sso-bootstrap.nix
    ./services/media/downloads.nix
    ./services/media/movies-tv.nix
    ./services/media/bazarr-bootstrap.nix
    ./services/media/arr-download-clients.nix
    ./services/media/prowlarr-bootstrap.nix
    ./services/media/configarr.nix
    ./services/media/qbit-manage.nix
    ./services/media/unpackerr.nix
    ./services/media/seerr-bootstrap.nix
    ./services/media/smoke-test.nix
    ./services/media/books.nix
    ./services/media/music.nix
    ./services/media/wizarr.nix
    ./services/media/cleanuparr.nix
    ./services/ingress.nix
    ./services/security.nix
    ./services/authelia.nix
    ./services/dashboard.nix
  ];

  networking.hostName = "media-node";

  homeOps = {
    secrets.enable = true;

    nas = {
      enable = true;
      host = "10.10.10.2";
      export = "/volume1/media-stack";
      mountPoint = "/mnt/nas/data";
    };

    media = {
      shared.enable = true;
      jellyfinBootstrap.enable = true;
      jellyfinPlugins.enable = true;
      jellyfinSsoBootstrap.enable = true;

      downloads = {
        sabnzbd.enable = true;
        qbittorrent.enable = true;
      };

      moviesTv.enable = true;
      bazarrBootstrap.enable = true;
      arrDownloadClients.enable = true;
      prowlarrBootstrap.enable = true;
      configarr.enable = true;
      qbitManage.enable = true;
      unpackerr.enable = true;
      seerrBootstrap.enable = true;
      smokeTest.enable = true;
      books.enable = true;
      music.enable = true;
      wizarr.enable = true;
      cleanuparr.enable = true;
    };

    dashboard.enable = true;

    ingress = {
      enable = true;
      jellyfinHost = "media.lawing.net";
      booksHost = "books.lawing.net";
    };

    security.enable = true;

    authelia = {
      enable = true;
      protectedHosts = [
        "home.lawing.net"
        "books.lawing.net"
      ];
    };
  };

  services.caddy.email = "vblawing@gmail.com";

  # Cloudflare API token is operator-provisioned on the box, not autogenerated:
  #   install -m 600 /dev/stdin /var/lib/home-ops/secrets/cloudflare-token <<< "<token>"
  # A records for all listed hostnames must already exist in Cloudflare —
  # this service only UPDATES existing records to the current IP.
  services.cloudflare-dyndns = {
    enable = true;
    apiTokenFile = "/var/lib/home-ops/secrets/cloudflare-token";
    domains = [
      "media.lawing.net"
      "auth.lawing.net"
      "home.lawing.net"
      "invite.lawing.net"
      "books.lawing.net"
    ];
    proxied = false;
  };

  system.stateVersion = "26.05";
}
